name: 🧪 Run Unit Tests

on: [push, pull_request]

jobs:
  Tests:
    name: Run All Tests on 4.2
    runs-on: ubuntu-latest
    # TODO: Replace with barichello after this PR (https://github.com/abarichello/godot-ci/pull/106) gets merged
    container: adrasteondev/godot-ci:mono-4.2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          dotnet restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug

      - name: Compile
        run: dotnet build

      - name: Run
        run: godot addons/WAT/cli.tscn run=all

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: tests/results.xml
